# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b7b4db85dfac0213c7ca9837687568ad13c4d9d2532eaa08bb99e33f57213a4da646d496e9b61b1ea5b234e65800ead18c0ce4e780669143e7c9e4af37f197

test:
  secret_key_base: e7a86e484156232affdc27874a62c7438e9b8a7d7efc878bcf8e82722774f99af2f4572f455a0f85d27bfea1fedf77fab5405bde6b8be36d3b94770054dee526

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
